# This script was generated by combining and prefixing multiple files.

# --- Combined External Imports ---
# No external imports found.

# -------------------- Content from: test3.py --------------------
mod_106ea677_B = 3
# -------------------- Content from: main.py --------------------
print(mod_106ea677_B)
print('Test!')

# --- End of combined script ---