site_name: DishPy Docs
theme:
  name: shadcn
  icon: none
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_labels: false
            docstring_style: google
            show_source: false
            show_root_heading: true
            heading_level: 2
